# Change these first
owner: joshahubbers # Your GitHub organization or username, where this repository lives
repo: DvO-uptime # The name of this repository

sites:
  - name: Amersfoort
    url: https://www.amersfoort.nl
  - name: Amstelveen
    url: https://www.amstelveen.nl
  - name: Bevelanden
    url: https://www.grdebevelanden.nl
  - name: Breda
    url: https://www.breda.nl
  - name: Dantumadiel
    url: https://www.dantumadiel.frl
  - name: Delft
    url: https://www.delft.nl
  - name: DvO Demo
    url: https://prod.dvgemdemo.hosted-temp.com
  - name: Edam-Volendam
    url: https://www.edam-volendam.nl
  - name: Eemsdelta
    url: https://www.eemsdelta.nl
  - name: Epe
    url: https://www.epe.nl
  - name: Gennep
    url: https://www.gennep.nl
  - name: Haarlem
    url: https://haarlem.nl
  - name: Krimpenerwaard
    url: https://www.krimpenerwaard.nl
  - name: Mechelen
    url: https://www.mechelen.be
  - name: Midden-Groningen
    url: https://www.midden-groningen.nl
  - name: Molenlanden
    url: https://www.molenlanden.nl
  - name: Montferland
    url: https://www.montferland.info
  - name: Noaberkracht
    url: https://www.dinkelland.nl
  - name: Noardeast-Fryslan
    url: https://www.noardeast-fryslan.nl
  - name: Noordenveld
    url: https://www.noordenveld.nl
  - name: Oude IJsselstreek
    url: https://www.oude-ijsselstreek.nl
  - name: Rijswijk
    url: https://www.rijswijk.nl
  - name: Rotterdam
    url: https://www.rotterdam.nl
  - name: Rotterdam stadsarchief
    url: https://stadsarchief.rotterdam.nl
  - name: Schagen
    url: https://www.schagen.nl
  - name: Venlo
    url: https://www.venlo.nl
  - name: Westerwolde
    url: https://www.westerwolde.nl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /DvO-uptime
  logoUrl: /upptime-icon.svg
  name: DvO uptime
  introTitle: "**DvO uptime** is the open-source uptime monitor and status page for DvO websites, powered entirely by GitHub."
  introMessage: Here you can see the **real-time** data from our [DvO status](https://joshahubbers.github.io/DvO-uptime/).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
